config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, :inclusion => { :in => %w(chinese italian japanese french belgian),
    :message => "not valid" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: {
    only_integer: true,
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_rest, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(rest_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(rest_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def rest_params
    params.require(:restaurant).permit(
      :name,
      :address,
      :phone_number,
      :category
    )
  end

  def set_rest
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end
end

private

def review_params
  params.require(:review).permit(:content, :rating)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'shared/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category %>
      <%= f.submit "Submit restaurant", class: "btn btn-primary" %>
    <% end %>
    <div>
      <%= link_to 'Back', restaurants_path %>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>

<%= render "form" %>

app/views/restaurants/index.html.erb
<h2>Restaurants</h2>
<div class="card">
  <div class="card-body">
    <ul>
      <% @restaurants.each do |restaurant| %>
        <li>
          <%= link_to restaurant.name, restaurant_path(restaurant) %>
            -  <%= restaurant.category %>
        </li>
      <% end %>
    </ul>
    <div>
      <%= link_to "New restaurant", new_restaurant_path %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= render "form" %>

app/views/restaurants/show.html.erb
<div class="card">
  <div class="card-body">

    <div>
      <h2><%= @restaurant.name %></h2>
      <address>
        <p>Address: <%= @restaurant.address %></p>
        <p>Tel: <%= @restaurant.phone_number %></p>
        <p>Type: <%= @restaurant.category %></p>
      </address>
    </div>
      <p>
        <%= link_to 'Back', restaurants_path %>   |
        <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>   |
        <%= link_to "Delete",
                restaurant_path(@restaurant),
                method: :delete,
                data: { confirm: "Are you sure" } %>
      </p>
      <h5>Reviews</h5>
      <ul class="list-group">
        <% @restaurant.reviews.each do |r| %>
        <li class="list-group-item">
          <%= r.content %> -
          Rating: <%= r.rating %> / 5 |
          <%= link_to "Remove", review_path(r),
          method: :delete,
          data: { confirm: "Are you sure?"} %>
        </li>
        <% end %>
        <p>
          <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
        </p>
      </ul>
    </div>

  </div>
</div>

app/views/reviews/new.html.erb
<div class="card">
  <div class="card-body">
    <h3>Write a review</h3>

    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">
    <%= link_to 'Yelp', restaurants_path %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "New", new_restaurant_path %>
      </li>
    </ul>
  </div>
</nav>